//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_AttributeTypes
    {
        public MST_AttributeTypes()
        {
            this.MST_Attributes = new HashSet<MST_Attributes>();
        }
    
        public int AttributeTypeId { get; set; }
        public string AttributeTypeName { get; set; }
        public string AttributeTypeCode { get; set; }
    
        public virtual ICollection<MST_Attributes> MST_Attributes { get; set; }
    }
}
