//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Functionality
    {
        public MST_Functionality()
        {
            this.Tran_EmailConfiguration = new HashSet<Tran_EmailConfiguration>();
        }
    
        public int FunctionalityId { get; set; }
        public string FunctionalityName { get; set; }
        public string FunctionalityCode { get; set; }
    
        public virtual ICollection<Tran_EmailConfiguration> Tran_EmailConfiguration { get; set; }
    }
}
