//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Project_Temp
    {
        public int ProjectId { get; set; }
        public int AccountId { get; set; }
        public string ProjectName { get; set; }
        public int IDPId { get; set; }
        public int EMId { get; set; }
        public int PMId { get; set; }
        public Nullable<bool> IsStrategic { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastDEReviewDate { get; set; }
        public Nullable<System.DateTime> LastIDQADate { get; set; }
        public Nullable<System.DateTime> LastSMRDate { get; set; }
    
        public virtual MST_Account MST_Account { get; set; }
        public virtual MST_Employee MST_Employee { get; set; }
        public virtual MST_Employee MST_Employee1 { get; set; }
        public virtual MST_IDP MST_IDP { get; set; }
    }
}
