//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_IDP
    {
        public MST_IDP()
        {
            this.MST_Employee = new HashSet<MST_Employee>();
            this.MST_Project = new HashSet<MST_Project>();
            this.MST_Questionnaire = new HashSet<MST_Questionnaire>();
            this.MST_Project_Temp = new HashSet<MST_Project_Temp>();
            this.Tran_IDP_Attributes = new HashSet<Tran_IDP_Attributes>();
        }
    
        public int IDPId { get; set; }
        public string IDPName { get; set; }
        public Nullable<int> LastUpdateBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual ICollection<MST_Employee> MST_Employee { get; set; }
        public virtual ICollection<MST_Project> MST_Project { get; set; }
        public virtual ICollection<MST_Questionnaire> MST_Questionnaire { get; set; }
        public virtual ICollection<MST_Project_Temp> MST_Project_Temp { get; set; }
        public virtual ICollection<Tran_IDP_Attributes> Tran_IDP_Attributes { get; set; }
    }
}
