//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Project
    {
        public MST_Project()
        {
            this.Tran_Proj_IDP_Attributes = new HashSet<Tran_Proj_IDP_Attributes>();
            this.Tran_DE_Calendar = new HashSet<Tran_DE_Calendar>();
            this.Tran_Proj_DE_Review = new HashSet<Tran_Proj_DE_Review>();
            this.Tran_Proj_Wkly_Status = new HashSet<Tran_Proj_Wkly_Status>();
        }
    
        public int ProjectId { get; set; }
        public string ProjectCode { get; set; }
        public int AccountId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> IDPId { get; set; }
        public Nullable<int> EMId { get; set; }
        public Nullable<int> PMId { get; set; }
        public Nullable<int> GeoId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MethodologyId { get; set; }
        public Nullable<int> NoWId { get; set; }
        public Nullable<int> EstBasisId { get; set; }
        public Nullable<System.DateTime> LastDEReviewDate { get; set; }
        public Nullable<System.DateTime> LastIDQADate { get; set; }
        public Nullable<System.DateTime> LastSMRDate { get; set; }
        public Nullable<bool> IsStrategic { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
    
        public virtual MST_Account MST_Account { get; set; }
        public virtual MST_Employee MST_Employee { get; set; }
        public virtual MST_Employee MST_Employee1 { get; set; }
        public virtual MST_EstBasis MST_EstBasis { get; set; }
        public virtual MST_Geo MST_Geo { get; set; }
        public virtual MST_IDP MST_IDP { get; set; }
        public virtual MST_Methodology MST_Methodology { get; set; }
        public virtual MST_NoW MST_NoW { get; set; }
        public virtual MST_Sector MST_Sector { get; set; }
        public virtual ICollection<Tran_Proj_IDP_Attributes> Tran_Proj_IDP_Attributes { get; set; }
        public virtual ICollection<Tran_DE_Calendar> Tran_DE_Calendar { get; set; }
        public virtual ICollection<Tran_Proj_DE_Review> Tran_Proj_DE_Review { get; set; }
        public virtual ICollection<Tran_Proj_Wkly_Status> Tran_Proj_Wkly_Status { get; set; }
    }
}
