//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_ReviewType
    {
        public MST_ReviewType()
        {
            this.MST_Questionnaire = new HashSet<MST_Questionnaire>();
        }
    
        public int ReviewTypeId { get; set; }
        public string ReviewTypeName { get; set; }
    
        public virtual ICollection<MST_Questionnaire> MST_Questionnaire { get; set; }
    }
}
