//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_AttributeValues
    {
        public int AttributeId { get; set; }
        public string AttributeValue { get; set; }
        public string AttributeText { get; set; }
        public int AttributeValueId { get; set; }
    }
}
