//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Employee
    {
        public MST_Employee()
        {
            this.MST_Project = new HashSet<MST_Project>();
            this.MST_Project1 = new HashSet<MST_Project>();
            this.MST_Project_Temp = new HashSet<MST_Project_Temp>();
            this.MST_Project_Temp1 = new HashSet<MST_Project_Temp>();
            this.Tran_DE_Calendar = new HashSet<Tran_DE_Calendar>();
            this.Tran_EmailConfiguration = new HashSet<Tran_EmailConfiguration>();
        }
    
        public int EmployeeId { get; set; }
        public Nullable<int> IDPId { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string EmailId { get; set; }
        public bool IsActive { get; set; }
        public string EmployeeCode { get; set; }
        public string WindowsId { get; set; }
    
        public virtual MST_IDP MST_IDP { get; set; }
        public virtual ICollection<MST_Project> MST_Project { get; set; }
        public virtual ICollection<MST_Project> MST_Project1 { get; set; }
        public virtual ICollection<MST_Project_Temp> MST_Project_Temp { get; set; }
        public virtual ICollection<MST_Project_Temp> MST_Project_Temp1 { get; set; }
        public virtual ICollection<Tran_DE_Calendar> Tran_DE_Calendar { get; set; }
        public virtual ICollection<Tran_EmailConfiguration> Tran_EmailConfiguration { get; set; }
    }
}
