//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Flags
    {
        public MST_Flags()
        {
            this.Tran_Proj_DE_Attibute = new HashSet<Tran_Proj_DE_Attibute>();
            this.Tran_Proj_Wkly_Attributes_Status = new HashSet<Tran_Proj_Wkly_Attributes_Status>();
            this.Tran_Proj_Wkly_Status = new HashSet<Tran_Proj_Wkly_Status>();
            this.Tran_Proj_Wkly_Status1 = new HashSet<Tran_Proj_Wkly_Status>();
        }
    
        public int FlagId { get; set; }
        public string FlagName { get; set; }
        public string ImagePath { get; set; }
        public string LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual ICollection<Tran_Proj_DE_Attibute> Tran_Proj_DE_Attibute { get; set; }
        public virtual ICollection<Tran_Proj_Wkly_Attributes_Status> Tran_Proj_Wkly_Attributes_Status { get; set; }
        public virtual ICollection<Tran_Proj_Wkly_Status> Tran_Proj_Wkly_Status { get; set; }
        public virtual ICollection<Tran_Proj_Wkly_Status> Tran_Proj_Wkly_Status1 { get; set; }
    }
}
