//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MST_Compliance
    {
        public MST_Compliance()
        {
            this.Tran_Compliance_DrpValues = new HashSet<Tran_Compliance_DrpValues>();
        }
    
        public int ComplianceId { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string TextValue { get; set; }
    
        public virtual ICollection<Tran_Compliance_DrpValues> Tran_Compliance_DrpValues { get; set; }
    }
}
