//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_DE_Calendar
    {
        public Tran_DE_Calendar()
        {
            this.Tran_Proj_DE_Review = new HashSet<Tran_Proj_DE_Review>();
        }
    
        public int DEReviewCalendarId { get; set; }
        public int ProjectId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int ReviewStatusId { get; set; }
    
        public virtual MST_Employee MST_Employee { get; set; }
        public virtual MST_Project MST_Project { get; set; }
        public virtual MST_ReviewStatus MST_ReviewStatus { get; set; }
        public virtual ICollection<Tran_Proj_DE_Review> Tran_Proj_DE_Review { get; set; }
    }
}
