//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_Compliance_DrpValues
    {
        public int DrpValueId { get; set; }
        public int ComplianceId { get; set; }
        public string DrpValues { get; set; }
    
        public virtual MST_Compliance MST_Compliance { get; set; }
    }
}
