//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_Proj_Wkly_Status
    {
        public Tran_Proj_Wkly_Status()
        {
            this.Tran_Proj_Wkly_Attributes_Status = new HashSet<Tran_Proj_Wkly_Attributes_Status>();
        }
    
        public int WeeklyStatusId { get; set; }
        public int WeekId { get; set; }
        public System.DateTime WeekStartDate { get; set; }
        public int Year { get; set; }
        public int ProjectId { get; set; }
        public int PriorOverallStatusId { get; set; }
        public int CurrentOverallStatusId { get; set; }
        public string LatestUpdates { get; set; }
        public string RiskItems { get; set; }
        public string IssueItems { get; set; }
        public string CorrectiveActions { get; set; }
        public Nullable<int> OverrideStatusId { get; set; }
        public Nullable<int> FlagsUpdatedByLevel { get; set; }
        public Nullable<int> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> LastUpdatedDate { get; set; }
    
        public virtual MST_Flags MST_Flags { get; set; }
        public virtual MST_Flags MST_Flags1 { get; set; }
        public virtual MST_Project MST_Project { get; set; }
        public virtual ICollection<Tran_Proj_Wkly_Attributes_Status> Tran_Proj_Wkly_Attributes_Status { get; set; }
    }
}
