//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryPortalDL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tran_EmailConfiguration
    {
        public int EmailConfigId { get; set; }
        public Nullable<int> FunctionalityId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual MST_Employee MST_Employee { get; set; }
        public virtual MST_Functionality MST_Functionality { get; set; }
    }
}
